### ISSUE TITLE
Error: Contig File does not exist!

### ISSUE THREAD

**Issue by mcmuufa** [bioinfomaticsCSU/AMC#10]
mufeeda@mufeeda-Aspire-A514-53:~/Desktop/MAC-2.1$ ./MAC2.0 '/home/mufeeda/Desktop/MAC-2.1/input/contigs.fa' '/home/mufeeda/Desktop/MAC-2.1/input/outputGraph.fa' 
error: Contig File does not exist
I have put both query and ref fasta in input folder and run the MAC. Still it is showing error ' Contig file doesnot exist'. Please help me to rectify this issue
Thank you in advance

**Comment by LiTang1013** [comment]
您的邮件我已收到，谢谢！

**Comment by jmonroynieto** [comment]
To anyone facing this issue.

The files should be located under the subdirectory `./input` but the command argument is expected to only contain the filename and does not support paths.

In @mcmuufa​'s case, the command should have been:
```
cd ~/Desktop/MAC-2.1/
./MAC2.0 contigs.fa outputGraph.fa
```

**Comment by LiTang1013** [comment]
您的邮件我已收到，谢谢！

**Comment by mcmuufa** [comment]
Thank you.

**Comment by jmonroynieto** [comment]
That auto reply is the worst.
